title      : naujgnaw sdrawkcab
lang       : zh
description: actually a page in the Internet
copyright  : © 2021 naujgnaw All Rights Reserved


permalink: pretty

nav:
 - name: 主页
   link: /
 - name: 梦
   link: /dreams/
 - name: 箱
   link: /sandbox/
 - name: 林
   link: /forest/
 - name: 记
   link: /notebook/
 - name: 项
   link: /schedule/