title      : 
lang       : zh
description: 
copyright  : © 2018 - 2021 naujgnaw All Rights Reserved

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
  
permalink: pretty
collections:
  dreams:
    output: true
    permalink: /:collection/:year/:month/:day/:title
  sandbox:
    output: true
    permalink: /:collection/:year/:month/:day/:title
collections_dir: col
nav:
 - name: dreams
   link: /dreams
 - name: sandbox
   link: /sandbox