title      : 
lang       : zh
description: 
copyright  : © 2018 - 2021 naujgnaw All Rights Reserved

permalink: /:title
collections:
  - dreams
  - sandbox
collections_dir: col
nav:
 - name: dreams
   link: /dreams.html
 - name: sandbox
   link: /sandbox.html